### ISSUE TITLE
Playbook points to the wrong repository.

### ISSUE THREAD

**Issue by rousso** [OP-TED/eforms-docs#1]
The Antora playbook is actually not needed in this repository. However, if we want to keep it as a reference for people that try to build the eForms docs locally, we should at least fix the content source (url, start_path and branches).

https://github.com/OP-TED/eforms-docs/blob/03044a84c928335b63896c79d3f2d7ac8a0c058a/antora-playbook.yml#L7

**Comment by bertrand-lorentz** [comment]
This is fixed in commit e331f6b5fb944de2b9dc9720cf731d0592de0994.
I hadn't seen this issue beforehand, so I didn't reference it in the commit.
