### ISSUE TITLE
Notice type QS incorrectly listed as PIN instead of CN

### ISSUE THREAD

**Issue by JasperBeaurain** [OP-TED/eforms-docs#103]
In table 1 n this page: [https://docs.ted.europa.eu/eforms/latest/schema/schemas.html](https://docs.ted.europa.eu/eforms/latest/schema/schemas.html)
QS (Notice subtype 15) is listed as a Prior information notice, while it is a contract notice.

The sdk itself confirms that it is indeeed a CN: https://github.com/OP-TED/eForms-SDK/blob/develop/notice-types/notice-types.json

**Comment by bertrand-lorentz** [comment]
Thanks for your feedback.
The documentation pages have been corrected to be consistent with notice-types.json.
